### ISSUE TITLE
Slow throughput

### ISSUE THREAD

**Issue by qricambi** [fatedier/frp#864] opened 2018-08-01 14:35 UTC
**What version of frp are you using (./frpc -v or ./frps -v)?**
v0.20.0

**What operating system and processor architecture are you using (`go env`)?**
Windows amd64

**Configures you used:**
[common]
server_addr =  
server_port = 7000
tcp_mux = false ; with or without this one

[b35444c3-a35f-4580-9d33-61a96a0b8cd0]
type = tcp
remote_port = 9090
local_ip = 127.0.0.1
local_port = 62000

**Steps to reproduce the issue:**
One the 62000 port I have an http proxy, and when I connect  directly to it the download speed using fast.com is RIGHT.
But when I proxy through the server public IP I peak at 2.6 Mb/s and it seams that this 2Mb/s is the limit

**Describe the results you expected:**
I'm testing this with a google server that has considerably more download or upload bandwidth so I would like to recieve the same download speed that I have without frp.

What do you think is the problem, I would love even to have a hint to where to look in the code

**Comment by fatedier** [comment] 2018-08-01 14:56
Duplicate of #851 & #662

**Closed by fatedier** 2018-08-01 14:56 UTC

**Comment by qricambi** [comment] 2018-08-01 15:02
Sorry man, can't read chinese :(

**Comment by fatedier** [comment] 2018-08-01 15:14
Please keep watching #851, it's a same issue.
I will reply it if i have come to a conclusion, by the way, i am busy doing other projects and i'm not sure when it cloud be solved.
