### ISSUE TITLE
好像不支持指定出网 IP

### ISSUE THREAD

**Issue by xiaopiao5789** [fatedier/frp#1313] opened 2019-07-08 09:57 UTC
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.27.0

**What operating system and processor architecture are you using (`go env`)?**
\--

**Configures you used:**
\--

**Steps to reproduce the issue:**
\--

**Describe the results you received:**
\--

**Describe the results you expected:**
\--

**Additional information you deem important (e.g. issue happens only occasionally):**
未来是否有计划支持指定出网 IP，类似于 curl 的 CURLOPT_INTERFACE，感觉这个功能还是很必要的。

**Can you point out what caused this issue (optional)**
\--

**Comment by ChenWenBrian** [comment] 2019-07-11 09:59
同求，对于有多IP或者多网卡的机器而言，能指定出口IP，或者网卡确实非常方便

**Comment by fatedier** [comment] 2019-07-12 08:56
Duplicate of #1205

**Closed by fatedier** 2019-07-12 08:56 UTC
