### ISSUE TITLE
在windows 10系统环境下，提醒frpc.exe携带病毒

### ISSUE THREAD

**Issue by Tokily** [fatedier/frp#2111] opened 2020-11-25 07:58 UTC
**[REQUIRED] hat version of frp are you using** 

Version:

**[REQUIRED] What operating system and processor architecture are you using**
OS:
CPU architecture:

**[REQUIRED] description of errors**

**confile**

**log file**

**Steps to reproduce the issue**
1. 
2. 
3. 

**Supplementary information**

**Can you guess what caused this issue**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/fatedier/frp/issues?q=is%3Aissue)

**Comment by fatedier** [comment] 2020-11-25 08:11
Duplicate of #2095 #1204

**Closed by fatedier** 2020-11-25 08:11 UTC
