### ISSUE TITLE
Wrong TimeZone/TimeStamp in LogFile at Android/iOS Platform

### ISSUE THREAD

**Issue by Droid-MAX** [fatedier/frp#1972] opened 2020-09-07 06:24 UTC
https://github.com/golang/go/issues/20455

**Comment by fatedier** [comment] 2020-09-07 06:39
Thanks for your report. It seems not fixed by golang. Keep this issue open to track this issue.

**Comment by Droid-MAX** [comment] 2020-09-07 06:48
建议更新到go1.15以上版本

**Comment by fatedier** [comment] 2020-09-07 07:16
The issue is not closed. Are you sure go1.15 fixed this?

**Comment by Droid-MAX** [comment] 2020-09-07 09:54
还没，不过可以测试一下这个方法看看
import _ "time/tzdata"
-tags timetzdata

**Comment by fatedier** [comment] 2020-09-07 10:06
It will increase the compiled binary file size, it maybe not worth to do so.

**Comment by Droid-MAX** [comment] 2020-09-09 11:28
好像这么做并不能解决问题

**Closed** 2021-04-01 09:31 UTC
Labels: question
