### ISSUE TITLE
客户端无法自动重连到服务器

### ISSUE THREAD

**Issue by shegaoyuan** [fatedier/frp#1350] opened 2019-08-01 11:42 UTC
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
frpc 0.27.1

**What operating system and processor architecture are you using (`go env`)?**
官方编译release版本

**Configures you used:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
2019/08/01 19:28:28 [W] [service.go:130] reconnect to server error: i/o deadline reached
2019/08/01 19:28:58 [W] [service.go:130] reconnect to server error: i/o deadline reached
2019/08/01 19:29:28 [W] [service.go:130] reconnect to server error: i/o deadline reached
2019/08/01 19:29:58 [W] [service.go:130] reconnect to server error: i/o deadline reached
2019/08/01 19:30:28 [W] [service.go:130] reconnect to server error: i/o deadline reached
2019/08/01 19:30:58 [W] [service.go:130] reconnect to server error: i/o deadline reached
2019/08/01 19:31:28 [W] [service.go:130] reconnect to server error: i/o deadline reached
2019/08/01 19:31:58 [W] [service.go:130] reconnect to server error: i/o deadline reached
2019/08/01 19:32:28 [W] [service.go:130] reconnect to server error: i/o deadline reached
2019/08/01 19:32:58 [W] [service.go:130] reconnect to server error: i/o deadline reached

客户端无法自动重连到服务器，重启frpc后正常

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

**Comment by fatedier** [comment] 2019-08-01 11:44
Duplicate of #1267

**Closed by fatedier** 2019-08-01 11:44 UTC
