### ISSUE TITLE
自定义404页面似乎有问题

### ISSUE THREAD

**Issue by li-xunhuan** [fatedier/frp#1319] opened 2019-07-12 02:35 UTC
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**
- frps: 0.27.0
- frpc: 0.27.0

**Steps to reproduce the issue:**
1. 自定义404页面
2. 打开一个未被定义的二级域名
3. 404页面直接显示

出了页面的代码

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**

![1](https://user-images.githubusercontent.com/10476982/61098190-b6c32900-a490-11e9-8411-9b857f3e6416.png)
![2](https://user-images.githubusercontent.com/10476982/61098193-b6c32900-a490-11e9-9621-110a37464048.png)

**Comment by fatedier** [comment] 2019-07-12 03:06
Duplicate of #1240

**Closed by fatedier** 2019-07-12 03:06 UTC
