### ISSUE TITLE
frpc设置了useEncryption和useCompression没效果呢

### ISSUE THREAD

**Issue by MrLiuGangQiang** [fatedier/frp#3686] opened 2023-10-16 06:54 UTC
### Bug Description

客户端设置如下 但是服务端显示Encryption和Compression还是为false 请问我这是没设置对还是有问题

[[proxies]]
name = "公司路由.WEB"
type = "tcp"
localIP = "xxx"
localPort = 443
remotePort = 26081
transport.useEncryption = true
transport.useCompression = true

### frpc Version

0.52.1

### frps Version

0.52.1

### System Architecture

linux/amd64

### Configurations

[[proxies]]
name = "公司路由.WEB"
type = "tcp"
localIP = "xx"
localPort = 443
remotePort = 26081
transport.useEncryption = true
transport.useCompression = true

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment] 2023-10-16 06:59
Duplicate of https://github.com/fatedier/frp/issues/3677

**Closed** 2023-10-16 07:04 UTC
