### ISSUE TITLE
dashboard_passwd in config example,should change to dashboard_pwd

### ISSUE THREAD

**Issue by big-hippo** [fatedier/frp#757] opened 2018-05-09 08:08 UTC
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.18.0

**What operating system and processor architecture are you using (`go env`)?**
linux amd64

**Configures you used:**
dashboard_user = admin
dashboard_passwd = 123456

**Steps to reproduce the issue:**
1.login dashboard 
2.
3.

**Describe the results you received:**
password 123456 not effect

**Describe the results you expected:**
login success

**Additional information you deem important (e.g. issue happens only occasionally):**
password is admin by default

**Can you point out what caused this issue (optional)**
dashboard_passwd must be dashboard_pwd (frps_full.ini in releases)
somebody forgets to change the full config example

**Comment by fatedier** [comment] 2018-05-12 12:52
Duplicate of #748

**Closed by fatedier** 2018-05-12 12:52 UTC
