### ISSUE TITLE
Optional basic auth for admin UI

### ISSUE THREAD

**Issue by bngabor** [fatedier/frp#2381] opened 2021-05-09 17:47 UTC
If admin username and password is empty, then turn off the http basic auth for admin UI.

Alternatives:
- empty username and password
- new config record for auth turn on/off

admin_user = ""
admin_pwd = ""
or
admin_auth=false

If if could be optional, then we can use external authentication, with two factor, etc.

**Comment by fatedier** [comment] 2021-05-10 02:03
Duplicate of https://github.com/fatedier/frp/issues/2344

**Closed** 2021-05-10 02:03 UTC
