### ISSUE TITLE
Startup error on mipsel 0.32.0 frpc

### ISSUE THREAD

**Issue by NemoAlex** [fatedier/frp#1699] opened 2020-03-12 06:34 UTC
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)
(请不要在 issue 评论中出现无意义的 **加1**，**我也是** 等内容，将会被直接删除。)
(由于个人精力有限，和系统环境，网络环境等相关的求助问题请转至其他论坛或社交平台。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
both 0.32.0

**What operating system and processor architecture are you using (`go env`)?**
mipsel_24kc

**Configures you used:**
Doesn't matter

**Steps to reproduce the issue:**
1. Run frpc on openwrt device

**Describe the results you received:**
```
SIGILL: illegal instruction
PC=0x47a6cc m=0 sigcode=128

goroutine 1 [running, locked to thread]:
runtime.asyncPreempt()
  runtime/preempt_mipsx.s:40 +0x7c fp=0x1439f0c sp=0x1439e18 pc=0x47a6cc
errors.New(0x97c637, 0x31, 0xaccd70, 0x140e7b0)
  errors/errors.go:59 +0x38 fp=0x1439f20 sp=0x1439f10 pc=0x48ba5c
github.com/pquerna/cachecontrol/cacheobject.init()
  github.com/pquerna/cachecontrol@v0.0.0-20180517163645-1555304b9b35/cacheobject/directive.go:46 +0x3bc fp=0x1439f34 sp=0x1439f20 pc=0x7d7d24
runtime.doInit(0xd91f00)
  runtime/proc.go:5414 +0xcc fp=0x1439f48 sp=0x1439f34 pc=0x451378
runtime.doInit(0xd8f920)
  runtime/proc.go:5409 +0x80 fp=0x1439f5c sp=0x1439f48 pc=0x45132c
runtime.doInit(0xd93de0)
  runtime/proc.go:5409 +0x80 fp=0x1439f70 sp=0x1439f5c pc=0x45132c
runtime.doInit(0xd91ec0)
  runtime/proc.go:5409 +0x80 fp=0x1439f84 sp=0x1439f70 pc=0x45132c
runtime.doInit(0xd939c0)
  runtime/proc.go:5409 +0x80 fp=0x1439f98 sp=0x1439f84 pc=0x45132c
runtime.doInit(0xd94900)
  runtime/proc.go:5409 +0x80 fp=0x1439fac sp=0x1439f98 pc=0x45132c
runtime.doInit(0xd90780)
  runtime/proc.go:5409 +0x80 fp=0x1439fc0 sp=0x1439fac pc=0x45132c
runtime.main()
  runtime/proc.go:190 +0x22c fp=0x1439fec sp=0x1439fc0 pc=0x441d98
runtime.goexit()
  runtime/asm_mipsx.s:651 +0x4 fp=0x1439fec sp=0x1439fec pc=0x479f4c

r0   0x0  r1   0x4
r2   0x8  r3   0x77e29088
r4   0x8ed704 r5   0x1
r6   0x8  r7   0x5
r8   0x908100 r9   0xac33d0
r10  0x8  r11  0x0
r12  0xf6 r13  0x1
r14  0x0  r15  0xf7
r16  0x0  r17  0x15
r18  0xf9 r19  0x0
r20  0x140e7b0  r21  0x140e7b0
r22  0xd91f28 r23  0xdd0000
r24  0x1  r25  0x77f079cc
r26  0x0  r27  0x0
r28  0x77f3d2a0 r29  0x1439e18
r30  0x14000e0  r31  0x48ba5c
pc   0x47a6cc link 0x48ba5c
lo   0x0  hi   0x0
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
0.31.2 works fine

**Can you point out what caused this issue (optional)**
https://github.com/kuoruan/openwrt-frp/issues/10

**Comment by fatedier** [comment] 2020-03-12 13:28
Do you download the program from the release page? Maybe a issue to golang official repo.

**Comment by NemoAlex** [comment] 2020-03-13 03:06
Same on frp_0.32.0_linux_mips, downloaded from the release page.
Video: https://github.com/NemoAlex/files/raw/master/QQ20200313-105801-HD.mp4

**Comment by NemoAlex** [comment] 2020-03-13 04:14
Test out this build on mips_24kc, problem solved:
https://github.com/kuoruan/openwrt-frp/releases/tag/v0.32.0-3
@kuoruan What change did you make?

**Comment by kuoruan** [comment] 2020-03-13 04:31
This issue caused by golang 1.14, fallback to 1.13.8 fixed this.

**Comment by botsphp** [comment] 2020-03-15 11:55
em, the same issue with https://github.com/fatedier/frp/issues/1703

thanks for help.

**Comment by cccooo** [comment] 2020-03-15 15:36
the same error "SIGILL: illegal instruction" on the wndr4300 openwrt with mips 0.32.0 frpc

**Comment by fatedier** [comment] 2020-03-26 08:28
Releated golang issue https://github.com/golang/go/issues/37653, maybe fixed in Go1.14.1.

I will release a new version compiled with go1.14.1 later.

**Comment by zyfdegh** [comment] 2020-04-03 14:13
`go1.14.1` has released and it works for me now.

**Comment by botsphp** [comment] 2020-04-04 07:21
> `go1.14.1` has released and it works for me now.

Cool.

**Closed** 2020-04-05 11:46 UTC

**Comment by NemoAlex** [comment] 2020-04-07 02:42
I just tested v0.32.1 binary on mips, fixed.
