### ISSUE TITLE
MT7620 RAMIPS won't run the precompiled version

### ISSUE THREAD

**Issue by autocar23** [fatedier/frp#538] opened 2017-11-27 12:16 UTC
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
v0.13.0

**What operating system and processor architecture are you using (`go env`)?**
Openwrt 15.05.1   MT7620 RAMIPS

**Configures you used:**
none

**Steps to reproduce the issue:**
1. `` wget frp_0.13.0_linux_mips.tar.gz or frp_0.13.0_linux_mipsle.tar.gz``
2. ``tar -zxvf ``
3. `` ./frps``

**Describe the results you received:**
1. run mips version got error  : line 1: syntax error: unexpected "("
2. run mipsle version got error : Illegal instruction

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Can you point out what caused this issue (optional)**
maybe RAMIPS architecture just won't run the mipsle or mips version ? Try to compile it myself by adding it to ``openwrt-ramips-sdk/package`` then run ``make menuconfig`` but nothing shows up. Maybe consider adding a guid to how to compile by self ?

**Comment by J1aq1An** [comment] 2017-11-30 02:13
See https://github.com/nodejs/node/issues/4818

**Comment by fatedier** [comment] 2017-12-07 05:13
Duplicate of #245

**Closed by fatedier** 2017-12-07 05:13 UTC
