### ISSUE TITLE
dashboard Proxies 里没有xtcp统计

### ISSUE THREAD

**Issue by lyg4795** [fatedier/frp#3788] opened 2023-11-21 02:43 UTC
### Bug Description

dashboard Proxies 里没有xtcp统计

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

linux/amd64 Ubuntu20.04

### Configurations

在web界面没看到

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment] 2023-11-21 03:08
Duplicate of https://github.com/fatedier/frp/issues/2085

暂时没有计划

**Closed by fatedier** 2023-11-21 03:08 UTC
